# Generated by Django 5.0.1 on 2024-01-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_ideastar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='updated_date',
        ),
    ]
