# Generated by Django 5.0.1 on 2024-01-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('releaseDate', models.DateField()),
                ('genre', models.CharField(max_length=10)),
                ('rating', models.FloatField()),
                ('director', models.CharField(max_length=30)),
                ('actors', models.TextField()),
                ('time', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
