# Generated by Django 5.0.1 on 2024-01-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='releaseDate',
            field=models.IntegerField(),
        ),
    ]
