# Generated by Django 5.0.1 on 2024-01-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('범죄', '범죄'), ('SF', 'SF'), ('코미디', '코미디'), ('공포', '공포'), ('전쟁', '전쟁'), ('애니메이션', '애니메이션'), ('드라마', '드라마'), ('로맨스', '로맨스')], default='액션', max_length=10),
        ),
    ]
